---
- name: Створити прод-VM на Proxmox
  hosts: proxmox_api
  gather_facts: false
  vars:
    # Перенаправити provision role на прод-параметри
    pve_dev_vmid: "{{ pve_prod_vmid }}"
    pve_dev_vm_name: "{{ pve_prod_vm_name }}"
    dev_vm_cores: "{{ prod_vm_cores }}"
    dev_vm_cpu_type: "{{ prod_vm_cpu_type }}"
    dev_vm_memory_mb: "{{ prod_vm_memory_mb }}"
    dev_vm_disk_gb: "{{ prod_vm_disk_gb }}"
    dev_vm_bridge: "{{ prod_vm_bridge }}"
    dev_vm_vlan_tag: "{{ prod_vm_vlan_tag }}"
    dev_vm_ip_cidr: "{{ prod_vm_ip_cidr }}"
    dev_vm_gateway: "{{ prod_vm_gateway }}"
    dev_vm_dns: ["{{ prod_vm_dns }}"]
    dev_vm_user: "{{ prod_vm_user }}"
    dev_vm_user_ssh_public_key: "{{ prod_vm_user_ssh_public_key }}"
  roles:
    - provision
